name: Formal Verification

on:
  push:
    branches: [ "main" ]
    tags-ignore:
      - '**'
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_BUILD_JOBS: 2 

jobs:
  kani-proofs:
    name: Kani Model Checker
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Run Kani
      - name: Run Kani
        uses: model-checking/kani-github-action@v1.1
        with:
          # Enable the solver
          enable-prover: true

          # Pass your specific arguments here
          args: |
            --harness kani_verification_avx2 
            --output-format=terse 
            -j 2 
            --unstable stubbing

      # Cleanup
      - name: Cleanup Artifacts
        if: always()
        run: cargo clean
